export const ALL_PERMISSIONS = [
  // USUARIOS
  'USUARIO_CADASTRAR',
  'USUARIO_EDITAR',
  'USUARIO_EXCLUIR',
  'USUARIO_LISTAR',

  // CARGOS
  'CARGO_CADASTRAR',
  'CARGO_EDITAR',
  'CARGO_EXCLUIR',
  'CARGO_LISTAR',
  'CARGO_ATRIBUIR',

  // EMPRESTIMOS
  'EMPRESTIMO_SOLICITAR',
  'EMPRESTIMO_EDITAR',
  'EMPRESTIMO_EXCLUIR',
  'EMPRESTIMO_LISTAR',
  'EMPRESTIMO_LIBERAR',
  'EMPRESTIMO_LISTAR_TODOS',
  'EMPRESTIMO_EDITAR_TODOS',
  'EMPRESTIMO_EXCLUIR_TODOS',

  // ITENS DE PATRIMONIO
  'ITEM_PATRIMONIO_CADASTRAR',
  'ITEM_PATRIMONIO_EDITAR',
  'ITEM_PATRIMONIO_EXCLUIR',
  'ITEM_PATRIMONIO_LISTAR',

  // PATRIMONIO
  'PATRIMONIO_CADASTRAR',
  'PATRIMONIO_EDITAR',
  'PATRIMONIO_EXCLUIR',
  'PATRIMONIO_LISTAR',

  // CATEGORIAS
  'CATEGORIA_CADASTRAR',
  'CATEGORIA_EDITAR',
  'CATEGORIA_EXCLUIR',
  'CATEGORIA_LISTAR',
] as const;

export type Permission = typeof ALL_PERMISSIONS[number];